# Generated by Django 4.0.1 on 2022-01-21 08:33

import django.core.validators
from django.db import migrations, models
import mysite.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='image',
            field=models.FileField(null=True, upload_to=mysite.utils.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='music',
            name='file',
            field=models.FileField(upload_to=mysite.utils.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
    ]
